using CDPIUI.Core.Basic;
using CDPIUI.Core.Data;
using CDPIUI.Core.JSON;
using CDPIUI.Core.Store.Database;
using CDPIUI.Shared;
using System.Security.Cryptography;
using System.Text;

namespace CDPIUI.Core.ComponentServices.Helpers.Configuration.Converters;

/// <summary>
/// Projects Zapret1 configs into Zapret2 and maintains their private converted file environment.
/// Native Zapret2 configs skipped
/// </summary>
public static class Zapret2LegacyConfigService
{
    public const string HashValidationSettingsGroup = "ZAPRET2";
    public const string HashValidationSettingsKey = "validateLegacyCacheHashes";
    public const bool DefaultHashValidationValue = true;

    private const string CacheFormatVersion = "1";
    private static readonly object SyncRoot = new();

    public static string CacheRoot =>
        Path.Combine(Directories.StoreItemsDirectory, SharedConstants.ConvertedZapretStoreItemId);

    public static void EnsureStorageRegistered(string? applicationVersion = null)
    {
        lock (SyncRoot)
        {
            Directory.CreateDirectory(CacheRoot);

            string currentApplicationVersion = applicationVersion ??
                DatabaseHelper.Instance.GetItemById(SharedConstants.ApplicationStoreId)?.CurrentVersion ??
                typeof(Zapret2LegacyConfigService).Assembly.GetName().Version?.ToString() ??
                string.Empty;

            DatabaseStoreItem? current =
                DatabaseHelper.Instance.GetItemById(SharedConstants.ConvertedZapretStoreItemId);

            if (current != null &&
                string.Equals(current.Directory, CacheRoot, StringComparison.OrdinalIgnoreCase) &&
                string.Equals(current.Type, "CDPIUIUpdateItem", StringComparison.Ordinal) &&
                string.Equals(current.Developer, "Autogenerated", StringComparison.Ordinal) &&
                string.Equals(current.CurrentVersion, currentApplicationVersion, StringComparison.Ordinal))
            {
                return;
            }

            DatabaseStoreItem cacheItem = new()
            {
                Id = SharedConstants.ConvertedZapretStoreItemId,
                Type = "CDPIUIUpdateItem",
                Directory = CacheRoot,
                Executable = null,
                UpdateCheckUrl = null,
                DownloadUrl = null,
                DownloadFileType = null,
                VersionControlType = "local",
                CurrentVersion = currentApplicationVersion,
                RequiredItemIds = null,
                DependentItemIds = null,
                IconPath = "$STATICIMAGE(Store/empty.png)",
                Name = "Zapret1 to Zapret2 converted config storage",
                ShortName = "Converted Zapret configs",
                Developer = "Autogenerated",
                BackgroudColor = string.Empty
            };

            if (!DatabaseHelper.Instance.AddOrUpdateItem(cacheItem))
            {
                throw new InvalidOperationException(
                    $"Cannot register the '{SharedConstants.ConvertedZapretStoreItemId}' store item.");
            }
        }
    }

    public static string GetStartupString(
        ConfigItem config,
        string expandedLegacyStartupString,
        bool validateHashes,
        bool forceRebuild = false)
    {
        ArgumentNullException.ThrowIfNull(config);

        if (!config.IsLegacy)
        {
            return expandedLegacyStartupString;
        }

        if (string.IsNullOrWhiteSpace(config.packId) || string.IsNullOrWhiteSpace(config.file_name))
        {
            throw new InvalidOperationException("The legacy config has no pack or file identifier.");
        }

        lock (SyncRoot)
        {
            EnsureStorageRegistered();

            string packDirectory = GetPackDirectory(config.packId);
            string legacyComponentDirectory = GetLegacyComponentDirectory();
            string cachePackDirectory = Path.Combine(CacheRoot, ToSafePathSegment(config.packId));
            string manifestDirectory = Path.Combine(cachePackDirectory, "_manifests");
            string manifestPath = Path.Combine(manifestDirectory, GetManifestFileName(config));

            ConvertedConfigManifest? existingManifest = LoadManifest(manifestPath);
            if (!forceRebuild && !validateHashes && IsCachePresent(existingManifest))
            {
                return existingManifest!.StartupString;
            }

            Dictionary<string, FileMapping> mappings =
                new(StringComparer.OrdinalIgnoreCase);

            string MapFile(string sourcePath)
            {
                if (!mappings.TryGetValue(sourcePath, out FileMapping? mapping))
                {
                    mapping = CreateFileMapping(
                        sourcePath,
                        packDirectory,
                        legacyComponentDirectory,
                        cachePackDirectory);
                    mappings.Add(sourcePath, mapping);
                }

                return mapping.DestinationPath;
            }

            ZapretConversionResult conversion = new Zapret1ToZapret2Converter(
                new ZapretConversionOptions { FilePathMapper = MapFile })
                .Convert(expandedLegacyStartupString);

            LogConversionWarnings(config, conversion.Issues);
            if (!conversion.IsSuccessful)
            {
                string errors = string.Join(
                    "; ",
                    conversion.Issues
                        .Where(issue => issue.Severity == ZapretConversionIssueSeverity.Error)
                        .Select(issue => $"{issue.Code}: {issue.Message}"));
                throw new InvalidOperationException(
                    $"Cannot convert legacy Zapret config '{config.name}': {errors}");
            }

            string inputHash = ComputeInputHash(
                config,
                expandedLegacyStartupString,
                conversion.ReferencedFiles,
                mappings,
                packDirectory);

            if (!forceRebuild && validateHashes &&
                existingManifest != null &&
                string.Equals(existingManifest.InputHash, inputHash, StringComparison.Ordinal) &&
                IsCachePresent(existingManifest))
            {
                return existingManifest.StartupString;
            }

            MaterializeFiles(conversion.ReferencedFiles, mappings);

            ConvertedConfigManifest newManifest = new()
            {
                CacheFormatVersion = CacheFormatVersion,
                PackId = config.packId,
                ConfigFileName = config.file_name,
                InputHash = inputHash,
                StartupString = conversion.StartupString,
                RequiredCachedFiles = GetRequiredCachedFiles(conversion.ReferencedFiles, mappings),
                ConvertedAtUtc = DateTime.UtcNow
            };

            Directory.CreateDirectory(manifestDirectory);
            SaveManifest(manifestPath, newManifest);
            return conversion.StartupString;
        }
    }

    private static string GetPackDirectory(string packId)
    {
        DatabaseStoreItem? item = DatabaseHelper.Instance.GetItemById(packId);
        return !string.IsNullOrWhiteSpace(item?.Directory)
            ? Path.GetFullPath(item.Directory)
            : Path.GetFullPath(Path.Combine(Directories.StoreItemsDirectory, packId));
    }

    private static string GetLegacyComponentDirectory()
    {
        const string legacyComponentId = "CSZTBN012";
        DatabaseStoreItem? item = DatabaseHelper.Instance.GetItemById(legacyComponentId);
        return !string.IsNullOrWhiteSpace(item?.Directory)
            ? Path.GetFullPath(item.Directory)
            : Path.GetFullPath(Path.Combine(Directories.StoreItemsDirectory, legacyComponentId));
    }

    private static FileMapping CreateFileMapping(
        string sourcePath,
        string packDirectory,
        string legacyComponentDirectory,
        string cachePackDirectory)
    {
        string normalized = Environment.ExpandEnvironmentVariables(
            sourcePath.Trim().Trim('"').TrimStart('@'));

        string absoluteSourcePath;
        if (Path.IsPathFullyQualified(normalized))
        {
            absoluteSourcePath = Path.GetFullPath(normalized);
        }
        else
        {
            string packCandidate = Path.GetFullPath(Path.Combine(packDirectory, normalized));
            string componentCandidate = Path.GetFullPath(Path.Combine(legacyComponentDirectory, normalized));
            absoluteSourcePath = File.Exists(packCandidate) || !File.Exists(componentCandidate)
                ? packCandidate
                : componentCandidate;
        }

        string destinationPath;
        if (TryGetRelativeChildPath(packDirectory, absoluteSourcePath, out string? packRelativePath))
        {
            destinationPath = Path.Combine(cachePackDirectory, "files", packRelativePath);
        }
        else if (TryGetRelativeChildPath(
            legacyComponentDirectory,
            absoluteSourcePath,
            out string? componentRelativePath))
        {
            destinationPath = Path.Combine(cachePackDirectory, "_component", componentRelativePath);
        }
        else
        {
            string pathHash = Convert.ToHexString(
                SHA256.HashData(Encoding.UTF8.GetBytes(absoluteSourcePath)))[..16].ToLowerInvariant();
            string fileName = Path.GetFileName(absoluteSourcePath);
            if (string.IsNullOrWhiteSpace(fileName))
            {
                fileName = "data.bin";
            }

            destinationPath = Path.Combine(cachePackDirectory, "_external", pathHash, fileName);
        }

        return new FileMapping(absoluteSourcePath, Path.GetFullPath(destinationPath));
    }

    private static bool TryGetRelativeChildPath(string root, string path, out string relativePath)
    {
        relativePath = Path.GetRelativePath(root, path);
        return !relativePath.Equals("..", StringComparison.Ordinal) &&
            !relativePath.StartsWith($"..{Path.DirectorySeparatorChar}", StringComparison.Ordinal) &&
            !Path.IsPathFullyQualified(relativePath);
    }

    private static void MaterializeFiles(
        IReadOnlyList<ZapretConversionFileReference> references,
        IReadOnlyDictionary<string, FileMapping> mappings)
    {
        foreach (IGrouping<string, ZapretConversionFileReference> group in references
            .GroupBy(reference => reference.ConvertedPath, StringComparer.OrdinalIgnoreCase))
        {
            ZapretConversionFileReference first = group.First();
            FileMapping mapping = mappings[first.SourcePath];
            string? destinationDirectory = Path.GetDirectoryName(mapping.DestinationPath);
            if (!string.IsNullOrWhiteSpace(destinationDirectory))
            {
                Directory.CreateDirectory(destinationDirectory);
            }

            bool needsInput = group.Any(reference => reference.Access != ZapretConversionFileAccess.Write);
            bool requiresExistingInput = group.Any(reference => reference.Access == ZapretConversionFileAccess.Read);

            if (requiresExistingInput && !File.Exists(mapping.SourcePath))
            {
                throw new FileNotFoundException(
                    $"A file used by the legacy Zapret config was not found: {mapping.SourcePath}",
                    mapping.SourcePath);
            }

            if (needsInput && File.Exists(mapping.SourcePath) &&
                !string.Equals(mapping.SourcePath, mapping.DestinationPath, StringComparison.OrdinalIgnoreCase))
            {
                File.Copy(mapping.SourcePath, mapping.DestinationPath, overwrite: true);
            }
        }
    }

    private static string ComputeInputHash(
        ConfigItem config,
        string expandedLegacyStartupString,
        IReadOnlyList<ZapretConversionFileReference> references,
        IReadOnlyDictionary<string, FileMapping> mappings,
        string packDirectory)
    {
        using IncrementalHash hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        AppendString(hash, CacheFormatVersion);
        AppendString(hash, config.packId ?? string.Empty);
        AppendString(hash, config.file_name ?? string.Empty);
        AppendString(hash, expandedLegacyStartupString);

        string configPath = Path.Combine(packDirectory, config.file_name!);
        AppendFile(hash, configPath, required: false);

        foreach (ZapretConversionFileReference reference in references
            .Where(reference => reference.Access != ZapretConversionFileAccess.Write)
            .OrderBy(reference => reference.SourcePath, StringComparer.OrdinalIgnoreCase)
            .ThenBy(reference => reference.Offset))
        {
            FileMapping mapping = mappings[reference.SourcePath];
            AppendString(hash, reference.OptionName);
            AppendString(hash, mapping.SourcePath);
            AppendString(hash, reference.Offset.ToString(global::System.Globalization.CultureInfo.InvariantCulture));
            AppendFile(
                hash,
                mapping.SourcePath,
                required: reference.Access == ZapretConversionFileAccess.Read);
        }

        return Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant();
    }

    private static void AppendString(IncrementalHash hash, string value)
    {
        byte[] data = Encoding.UTF8.GetBytes(value);
        hash.AppendData(BitConverter.GetBytes(data.Length));
        hash.AppendData(data);
    }

    private static void AppendFile(IncrementalHash hash, string path, bool required)
    {
        if (!File.Exists(path))
        {
            if (required)
            {
                throw new FileNotFoundException(
                    $"A file used by the legacy Zapret config was not found: {path}",
                    path);
            }

            AppendString(hash, "<missing>");
            return;
        }

        AppendString(hash, "<file>");
        using FileStream stream = File.OpenRead(path);
        byte[] buffer = new byte[81920];
        int read;
        while ((read = stream.Read(buffer, 0, buffer.Length)) > 0)
        {
            hash.AppendData(buffer, 0, read);
        }
    }

    private static List<string> GetRequiredCachedFiles(
        IReadOnlyList<ZapretConversionFileReference> references,
        IReadOnlyDictionary<string, FileMapping> mappings)
    {
        return references
            .Where(reference =>
                reference.Access == ZapretConversionFileAccess.Read ||
                (reference.Access == ZapretConversionFileAccess.ReadWrite &&
                    File.Exists(mappings[reference.SourcePath].SourcePath)))
            .Select(reference => reference.ConvertedPath)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static bool IsCachePresent(ConvertedConfigManifest? manifest)
    {
        return manifest != null &&
            manifest.CacheFormatVersion == CacheFormatVersion &&
            !string.IsNullOrWhiteSpace(manifest.StartupString) &&
            (manifest.RequiredCachedFiles?.All(File.Exists) ?? true);
    }

    private static ConvertedConfigManifest? LoadManifest(string manifestPath)
    {
        if (!File.Exists(manifestPath))
        {
            return null;
        }

        try
        {
            return JSONConvertor.LoadJson<ConvertedConfigManifest>(manifestPath);
        }
        catch (Exception ex)
        {
            Logger.Instance.CreateWarningLog(
                nameof(Zapret2LegacyConfigService),
                $"Cannot read converted Zapret manifest '{manifestPath}': {ex}");
            return null;
        }
    }

    private static void SaveManifest(string manifestPath, ConvertedConfigManifest manifest)
    {
        string temporaryPath = manifestPath + ".tmp";
        File.WriteAllText(temporaryPath, JSONConvertor.SerializeObject(manifest));
        File.Move(temporaryPath, manifestPath, overwrite: true);
    }

    private static string GetManifestFileName(ConfigItem config)
    {
        string identity = $"{config.packId}\0{config.file_name}";
        string hash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(identity)))
            [..20]
            .ToLowerInvariant();
        return $"{hash}.json";
    }

    private static string ToSafePathSegment(string value)
    {
        HashSet<char> invalidChars = [.. Path.GetInvalidFileNameChars()];
        string result = new(value.Select(character =>
            invalidChars.Contains(character) ? '_' : character).ToArray());
        return string.IsNullOrWhiteSpace(result) ? "unknown-pack" : result;
    }

    private static void LogConversionWarnings(
        ConfigItem config,
        IReadOnlyList<ZapretConversionIssue> issues)
    {
        foreach (ZapretConversionIssue issue in issues
            .Where(issue => issue.Severity == ZapretConversionIssueSeverity.Warning))
        {
            Logger.Instance.CreateWarningLog(
                nameof(Zapret2LegacyConfigService),
                $"Legacy config '{config.packId}/{config.file_name}': {issue.Code}: {issue.Message}");
        }
    }

    private sealed record FileMapping(string SourcePath, string DestinationPath);

    private sealed class ConvertedConfigManifest
    {
        public string CacheFormatVersion { get; set; } = string.Empty;
        public string PackId { get; set; } = string.Empty;
        public string ConfigFileName { get; set; } = string.Empty;
        public string InputHash { get; set; } = string.Empty;
        public string StartupString { get; set; } = string.Empty;
        public List<string>? RequiredCachedFiles { get; set; }
        public DateTime ConvertedAtUtc { get; set; }
    }
}
